apiVersion: v1
kind: Secret
metadata: 
  namespace: workshop
  name: mongo-sec
type: Opaque
data:  
  password: VGhyZWUtVGllci1Qcm9qZWN0Cg==         #cGFzc3dvcmQxM  #Three-Tier-Project
  username:  YWRtaW4K                                 #YWRtaW4= #admin
